title: Technical Minecraft Wiki
description: A new Minecraft wiki, dedicated to only explaining Technial Minecraft in an easy to edit format!

url: "techmcdocs.github.io"
plugins:
  - jekyll-sitemap

permalink: pretty
exclude:
  - README.md
  - .idea

keep_files: ["css","js"]

collections:
  basics:
    output: true
  tags:
    output: true
  filters:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default